import './globals.css'
import { Inter } from 'next/font/google'
import { Header } from './component/Header'

import { Mulish } from 'next/font/google'
import Footer from './component/Footer'

const roboto = Mulish({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})





export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
